### ISSUE TITLE
Improve the web page ui and make it responsive

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/HackRCDU#5]
Improve the Frontend and Make it Attractive and Responsive. :rainbow: This repo is open for quality contributions only not for 2-3lines tiny things.

**Comment by akankshast** [comment]
I would like to contribute to this issue.

**Comment by iampavangandhi** [comment]
Hey @akankshast, Yes you can contribute make sure to retain the responsiveness. All the best :+1:

**Comment by pineapple45** [comment]
Hey, if this issue is still open. Can I work on it?

**Comment by iampavangandhi** [comment]
@pineapple45 It's still open you can work

**Comment by pineapple45** [comment]
@iampavangandhi, please add "hacktoberfest" topic to the repo as well. Thanks

**Comment by iampavangandhi** [comment]
@pineapple45 The Hacktoberfest label is already present in the issue.

**Comment by fredoist** [comment]
@iampavangandhi organizers have made changes in the form our PRs count, now repository maintainers need to add the `hacktoberfest` topic in the repo in order to our PRs count as valid.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">UPDATE: We’re making Hacktoberfest opt-in only for projects – which maintainers can do simply by adding the ‘hacktoberfest’ topic to a repository! Thanks for your patience as we work on continually improving the Hacktoberfest experience. 💙🎉 <a href="https://t.co/hHKRgASoQw">https://t.co/hHKRgASoQw</a></p>&mdash; Hacktoberfest (@hacktoberfest) <a href="https://twitter.com/hacktoberfest/status/1312221208667185153?ref_src=twsrc%5Etfw">October 3, 2020</a></blockquote>

**Comment by Anurag-ak99** [comment]
hey @iampavangandhi can I work on the issue? Is it still open?

**Comment by iampavangandhi** [comment]
@Anurag-ak99 Yes It's open.

**Comment by Adityachaturvedi2906** [comment]
hey, can please assign me? I will try this out

**Comment by iampavangandhi** [comment]
@Adityachaturvedi2906 This issues is open for all and on a FCFS basis. Also, do proper testing of responsiveness before making PR and provide screenshots of what changes you did.

**Note:** This repo is open for quality contributions only not for 2-3lines tiny things.

**Comment by mayankmohak** [comment]
Is this issue still open i would like to work upon it.

**Comment by iampavangandhi** [comment]
@mayankmohak  This issues is open for all and on a FCFS basis. Also, do proper testing of responsiveness before making PR and provide screenshots of what changes you did.

**Note:** This repo is open for quality contributions only not for 2-3lines tiny things.

**Comment by rahulparmani** [comment]
@iampavangandhi Hi! If this issue is still open I would like to work on it. I will make sure to add quality contributions to it. Thanks.
